#!/bin/bash

echo "enter start_index end_index and data_dir respectively"

read -t 0 

python download.py --start_index $1 --end_index $2 --data_dir $3


export ds_dir="/iplant/home/shared/soynomics/inaturalist/downloaded_data/"
export local_dir="${3}/$1_$2.tar.gz"

iput -f $local_dir $ds_dir

rm -rf $local_dir


