#!/bin/bash

read -p "csv file without csv extention": csv_file
read -p "Data Store Directory": ds_dir

img2dataset --url_list=$csv_file\.csv --resize_mode=0 --input_format=csv --url_col=photo_url_large --output_folder=$csv_file --output_format=webdataset --number_sample_per_shard=2000

echo "saving to data store" 


# ds_dir: /iplant/home/shared/soynomics/inaturalist/downloaded_data


#irync -r ancestry i:$ds_dir
#iput -r $csv_file $ds_dir

rm -r $csv_file 
